apply plugin: 'com.android.library'

android {
    compileSdk 37
    namespace 'com.haibin.calendarview'
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }
    defaultConfig {
        minSdkVersion 17
        targetSdkVersion 36
        versionCode 371
        versionName "3.7.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled = true
    }
    buildTypes {
        release {
            minifyEnabled false
            consumerProguardFiles 'consumer-rules.pro'
        }
    }
    android {
        lintOptions {
            abortOnError false
        }
    }
    buildFeatures {
        viewBinding true
    }
    compileSdkMinor 0
    buildToolsVersion '37.0.0'
    ndkVersion '30.0.14904198 rc1'
    tasks.register('intoJar', Copy) {
        delete 'build/libs/CalendarView.jar'
        from('build/intermediates/bundles/release/')
        into('build/libs/')
        include('classes.jar')
        rename('classes.jar', 'CalendarView.jar')
    }
    intoJar.dependsOn(build)
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation('androidx.test.espresso:espresso-core:3.7.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation libs.appcompat
    implementation libs.recyclerview
//    testImplementation libs.junit.v412
}